[minio]
type = s3
provider = Minio
access_key_id = minioadmin
secret_access_key = minioadmin
endpoint = http://minio:9000
acl = private

[ceph]
type = s3
provider = Ceph
access_key_id = cephlab
secret_access_key = cephlabsecret
endpoint = http://ceph:8080
acl = private
